name: Releases

on:
  push:
    tags: 
    - '*'

jobs:
  
  build:
    runs-on: windows-latest
    steps:
    
    - name: Create Release
      uses: ncipollo/release-action@v1.7.3
      with:
        artifact: "AmagnoPrinterInstaller.msi"
        token: ${{ secrets.GITHUB_TOKEN }}